"""Symbol was added to the table game_result

Revision ID: d561ac117620
Revises: 94251acc9253
Create Date: 2020-08-09 02:58:49.438202

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d561ac117620"
down_revision = "94251acc9253"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game_result", sa.Column("symbol", sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_result", "symbol")
    # ### end Alembic commands ###
