# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "develop" ]
  # pull_request:
  #   branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv setuptools
        python -m pip install --upgrade pipenv
        pipenv install --system --deploy
    # - name: Lint all set of linters
    #   run: |
    #     pipenv run lint
    - name: Test with pytest
      run: |
        pipenv run unit
    - name: Count coverage
      run: |
        echo ${$(pipenv run coverage | grep TOTAL): -1}
