# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "develop" ]
  # pull_request:
  #   branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv setuptools
        python -m pip install --upgrade pipenv
        pipenv install --system --deploy --dev
    # - name: Lint all set of linters
    #   run: |
    #     pipenv run lint
    - name: Test with pytest
      run: |
        pipenv run unit
        pipenv run coverage_json
    - name: Count coverage
      run: |
        echo "COVERAGE=$(pipenv run coverage | awk '$1 == "TOTAL" {print $NF+0}')" >> $GITHUB_ENV
    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: e8d23650144c1dd611a941789d52721a
        filename: coverage.json
        label: Test Coverage
        message: ${{ env.COVERAGE }}
        namedLogo: pytest
        logoColor: lightblue
        valColorRange: ${{ env.COVERAGE }}
        maxColorRange: 100
        minColorRange: 50
